# Set latexmk to call lualatex instead of pdflatex for compiling Feynman diags
$pdflatex = "lualatex -file-line-error -shell-escape";

# Need to turn of ps and dvi generation for lualatex, if you want these you'll
# need to convert the pdf later.
$pdf_mode = 1;
$postscript_mode = 0;
$dvi_mode = 0;

# Set extensions for cleanup when using -c option
push @generated_exts, 'auxlock', 'synctex.gz', 'figlist', 'ist', 'makefile', 'unq', 'nav', 'snm', 'fls';

# Make latex find files needed for the theme
$ENV{TEXINPUTS} = ".:beamerthemeLMU:";

$ENV{max_print_line} = $log_wrap = 1000;


# add support for feynmp
add_cus_dep( 'mp', '1', 0, 'mpost' );
sub mpost {
    my $file = $_[0];
    my ($name, $path) =  fileparse( $file );
    my $return = system "mpost \"$file\"";
    # Fix the problem that mpost puts its output and log files
    # in the current directory, not in the auxiliary directory
    # (which is often the same as the output directory):
    move "$name.1", $path;
    move "$name.log", $aux_dir;
    return $return;
}
